defaults.url=https://sentry.io/
defaults.org=aavegotchi
defaults.project=realm-frontend
cli.executable=../../../../.npm/_npx/86738/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli
