name: Notify Sentry, S3 Sync

on:
  push:
    branches: ['alpha', 'development', 'staging', 'master']
  release:
    types: ['published']

env:
  SENTRY_LOG_LEVEL: "debug"

jobs:
  deploy:
    name: Notify Sentry, S3 Sync
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Set deploy environment if master
      if: github.ref_name == 'master'
      run: |
        echo "DEPLOY_ENV=production" >> $GITHUB_ENV
        echo "DEPLOY_ENV_COMMON_NAME=production" >> $GITHUB_ENV
        echo "DEPLOY_URL=https://verse.aavegotchi.com" >> $GITHUB_ENV
        echo "AARENA_DEPLOY_URL=https://aarena.aavegotchi.com" >> $GITHUB_ENV
        echo "S3_BUCKET_REGION=eu-west-2" >> $GITHUB_ENV
        echo "S3_BUCKET=verse-static.aavegotchi.com" >> $GITHUB_ENV

    - name: Set deploy environment if staging
      if: github.ref_name == 'staging'
      run: |
        echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
        echo "DEPLOY_ENV_COMMON_NAME=beta" >> $GITHUB_ENV
        echo "DEPLOY_URL=https://beta.gotchiverse.io" >> $GITHUB_ENV
        echo "AARENA_DEPLOY_URL=https://combat-beta.gotchiverse.io" >> $GITHUB_ENV
        echo "S3_BUCKET_REGION=ap-northeast-1" >> $GITHUB_ENV
        echo "S3_BUCKET=beta-verse-static.aavegotchi.com" >> $GITHUB_ENV

    - name: Set deploy environment if alpha
      if: github.ref_name == 'alpha'
      run: |
        echo "DEPLOY_ENV=alpha" >> $GITHUB_ENV
        echo "DEPLOY_ENV_COMMON_NAME=alpha" >> $GITHUB_ENV
        echo "DEPLOY_URL=https://alpha.gotchiverse.io" >> $GITHUB_ENV
        echo "AARENA_DEPLOY_URL=https://combat-alpha.gotchiverse.io" >> $GITHUB_ENV
        echo "S3_BUCKET_REGION=ap-northeast-1" >> $GITHUB_ENV
        echo "S3_BUCKET=beta-verse-static.aavegotchi.com" >> $GITHUB_ENV

    - name: Set deploy environment if development
      if: github.ref_name == 'development'
      run: |
        echo "DEPLOY_ENV=development" >> $GITHUB_ENV
        echo "DEPLOY_ENV_COMMON_NAME=development" >> $GITHUB_ENV
        echo "DEPLOY_URL=https://development.gotchiverse.io" >> $GITHUB_ENV
        echo "AARENA_DEPLOY_URL=https://combat-development.gotchiverse.io" >> $GITHUB_ENV
        echo "S3_BUCKET_REGION=ap-northeast-1" >> $GITHUB_ENV
        echo "S3_BUCKET=beta-verse-static.aavegotchi.com" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: ${{ env.DEPLOY_ENV }}

    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      if: github.ref_name == 'master' || github.ref_name == 'staging'
      with:
        args: --size-only --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.S3_BUCKET_REGION }}
        SOURCE_DIR: 'public'

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_DEPLOY_NOTE_WEBHOOK_URL }}
      uses: Ilshidur/action-discord@master
      with:
        args: '${{ github.event.repository.name }}''s latest ${{ github.ref_name }} branch (pusher: ${{github.event.pusher.name}} / hash: ${{github.event.after}} / message: [${{github.event.commits[0].message}}]) will be live on ${{ env.DEPLOY_URL }} and ${{ env.AARENA_DEPLOY_URL }} in about 3 minutes.'

